apiVersion: v1
kind: Service
metadata:
  name: node-metrics-app
  labels:
    app: node-metrics-app
spec:
  type: LoadBalancer
  ports:
    - port: 9991               # Updated port
      targetPort: 9991         # Updated port
      protocol: TCP
  selector:
    app: node-metrics-app

